
export const clientTemplateClientCertificate = JSON.stringify({
  clientId: '',
  name: '',
  description: '',
  surrogateAuthRequired: false,
  enabled: false,
  alwaysDisplayInConsole: false,
  clientAuthenticatorType: 'client-x509',
  redirectUris: ['http://*', 'https://*'],
  webOrigins: ['*'],
  notBefore: 0,
  bearerOnly: false,
  consentRequired: false,
  standardFlowEnabled: true,
  implicitFlowEnabled: false,
  directAccessGrantsEnabled: false,
  serviceAccountsEnabled: true,
  publicClient: false,
  frontchannelLogout: false,
  protocol: 'openid-connect',
  attributes: {
    "request.object.signature.alg": "any",
    "saml.multivalued.roles": "false",
    "saml.force.post.binding": "false",
    "oauth2.device.authorization.grant.enabled": "false",
    "backchannel.logout.revoke.offline.tokens": "false",
    "saml.server.signature.keyinfo.ext": "false",
    "use.refresh.tokens": "true",
    "realm_client": "false",
    "oidc.ciba.grant.enabled": "false",
    "backchannel.logout.session.required": "true",
    "client_credentials.use_refresh_token": "false",
    "saml.client.signature": "false",
    "require.pushed.authorization.requests": "false",
    "request.object.encryption.enc": "any",
    "dpop.bound.access.tokens": "false",
    "saml.assertion.signature": "false",
    "x509.subjectdn": "",
    "request.object.encryption.alg": "any",
    "client.introspection.response.allow.jwt.claim.enabled": "false",
    "saml.encrypt": "false",
    "standard.token.exchange.enabled": "true",
    "saml.server.signature": "false",
    "exclude.session.state.from.auth.response": "false",
    "client.use.lightweight.access.token.enabled": "false",
    "request.object.required": "not required",
    "saml_force_name_id_format": "false",
    "access.token.header.type.rfc9068": "false",
    "acr.loa.map": "{}",
    "tls.client.certificate.bound.access.tokens": "true",
    "saml.authnstatement": "false",
    "display.on.consent.screen": "false",
    "x509.allow.regex.pattern.comparison": "false",
    "token.response.type.bearer.lower-case": "false",
    "saml.onetimeuse.condition": "false"
  },
  authenticationFlowBindingOverrides: {},
  fullScopeAllowed: false,
  nodeReRegistrationTimeout: -1,
  protocolMappers: [] as any[],
  defaultClientScopes: [] as string[],
  optionalClientScopes: [] as string[],
  access: { view: true, configure: true, manage: true },
});
