
export const clientTemplateClientCertificate = JSON.stringify({
  access: { view: true, configure: true, manage: true },
  alwaysDisplayInConsole: false,
  authenticationFlowBindingOverrides: {},
  attributes: {
    "acr.loa.map": "{}",
    "access.token.header.type.rfc9068": false,
    "backchannel.logout.revoke.offline.tokens": false,
    "backchannel.logout.session.required": true,
    "client.introspection.response.allow.jwt.claim.enabled": false,
    "client.use.lightweight.access.token.enabled": false,
    "client_credentials.use_refresh_token": false,
    "display.on.consent.screen": false,
    "dpop.bound.access.tokens": false,
    "exclude.session.state.from.auth.response": false,
    "oauth2.device.authorization.grant.enabled": false,
    "oidc.ciba.grant.enabled": false,
    "realm_client": false,
    "request.object.encryption.alg": "any",
    "request.object.encryption.enc": "any",
    "request.object.required": "not required",
    "request.object.signature.alg": "any",
    "require.pushed.authorization.requests": false,
    "saml.client.signature": false,
    "saml.encrypt": false,
    "saml.assertion.signature": false,
    "saml.authnstatement": false,
    "saml.force.post.binding": false,
    "saml.multivalued.roles": false,
    "saml.onetimeuse.condition": false,
    "saml.server.signature": false,
    "saml.server.signature.keyinfo.ext": false,
    "saml_force_name_id_format": false,
    "standard.token.exchange.enabled": true,
    "tls.client.certificate.bound.access.tokens": true,
    "token.response.type.bearer.lower-case": false,
    "use.refresh.tokens": true,
    "x509.allow.regex.pattern.comparison": false,
    "x509.subjectdn": ""
  },
  bearerOnly: false,
  clientAuthenticatorType: 'client-x509',
  clientId: '',
  consentRequired: false,
  defaultClientScopes: [] as string[],
  description: '',
  directAccessGrantsEnabled: false,
  enabled: false,
  frontchannelLogout: false,
  fullScopeAllowed: false,
  implicitFlowEnabled: false,
  name: '',
  nodeReRegistrationTimeout: -1,
  notBefore: 0,
  optionalClientScopes: [] as string[],
  protocol: 'openid-connect',
  protocolMappers: [] as any[],
  publicClient: false,
  redirectUris: ['http://*', 'https://*'],
  serviceAccountsEnabled: false,
  standardFlowEnabled: true,
  surrogateAuthRequired: false,
  webOrigins: ['*'],
});
