sonar.organization=bcgov-sonarcloud
sonar.projectKey=bcgov_api-services-portal

sonar.sources=src/auth,src/authz,src/batch,src/services
sonar.javascript.lcov.reportPaths=./src/__coverage__/lcov.info

