FROM node:alpine

# WORKDIR /app

# COPY package*.json ./
# RUN npm install

# COPY *.js ./
# COPY app ./app
# COPY components ./components
# COPY lists ./lists
# COPY pages ./pages
# COPY public ./public

# ARG GITHUB_API_TOKEN
# ENV COOKIE_SECRET=change_me

# RUN npm run build

ENTRYPOINT [ "npm", "run" ]
CMD [ "start"]
