'use strict';

// Steps from documentation/how-to/sdx-org-onboarding.md.
//
// Every builder here takes `(ctx, overrides = {})` and returns a step
// object `{ id, title, group, fatal, run }`. `overrides` lets a scenario
// test inject one deliberately-wrong value (a bad role, a body override,
// ...) and/or an `onResult(res, ctx)` hook to assert on the restish
// response, without duplicating the step body.

const ROOT_ORG_DOMAIN = 'ca.bc.gov';

function createOrg(ctx, overrides = {}) {
  const { state } = ctx;
  const td = state.testData;
  return {
    id: overrides.id || 'org.create',
    title: 'Register new organization',
    fatal: overrides.fatal,
    run: async () => {
      const res = await ctx.call(
        overrides.id || 'org.create',
        state.orgAlias,
        ['put-organization', ROOT_ORG_DOMAIN],
        {
          body: {
            name: td.orgName,
            title: `SDX Test Org ${td.suffix}`,
            description:
              'Auto-generated by the SDX TechDocs test runner. Safe to delete.',
            extSource: 'sdx-techdocs-test-runner',
            extRecordHash: td.suffix,
            tags: [
              `member_class:${td.memberClass}`,
              `member_id:${td.memberId}`,
              `test_run:${td.suffix}`,
            ],
            orgUnits: [],
            ...overrides.body,
          },
        }
      );
      if (overrides.onResult) await overrides.onResult(res, ctx);
    },
  };
}

/**
 * "System Owner role assignment" (put-organization-access).
 *
 * `overrides.roles` defaults to the documented-correct `['system-admin']`;
 * pass e.g. `['system-owner']` to reproduce PLAT-001's silently-accepted
 * unsupported role.
 */
function orgAccess(ctx, overrides = {}) {
  const { state } = ctx;
  const td = state.testData;
  const roles = overrides.roles || ['system-admin'];
  return {
    id: overrides.id || 'org.access',
    title: 'System Owner role assignment',
    fatal: overrides.fatal !== undefined ? overrides.fatal : false,
    run: async () => {
      const res = await ctx.call(
        overrides.id || 'org.access',
        state.orgAlias,
        ['put-organization-access', ROOT_ORG_DOMAIN],
        {
          body: {
            name: td.orgName,
            parent: `/${ROOT_ORG_DOMAIN}`,
            members: [{ member: { email: state.memberEmail }, roles }],
          },
        }
      );
      if (overrides.onResult) await overrides.onResult(res, ctx);
    },
  };
}

function orgGateway(ctx, overrides = {}) {
  const { state } = ctx;
  const td = state.testData;
  return {
    id: overrides.id || 'org.gateway',
    title: 'Assign gateway for organization',
    fatal: overrides.fatal,
    run: async () => {
      const res = await ctx.call(
        overrides.id || 'org.gateway',
        state.sdxAlias,
        ['register-organization-gateway', td.orgName]
      );
      if (res.json && res.json.gatewayId) state.captured.orgGatewayId = res.json.gatewayId;
      if (overrides.onResult) await overrides.onResult(res, ctx);
    },
  };
}

module.exports = { ROOT_ORG_DOMAIN, createOrg, orgAccess, orgGateway };
