entity: CredentialIssuer
record:
  id: 'Shared IdP'
  namespace: platform
  description: 'Shared IdP Authorization Profile`
  flow: client-credentials
  mode: auto
  clientAuthenticator: client-secret
  authPlugin: jwt-keycloak
  clientRoles: []
  owner: api-owner@local
  isShared: true
  environmentDetails:
    - environment: prod
      issuerUrl: '{OIDC_ISSUER}'
      clientId: '{OIDC_CLIENT_ID}'
      clientSecret: '{OIDC_CLIENT_SECRET}'
      clientRegistration: managed
