
  mutation updateGatewayConsumerPlugin(
    $id: ID!
    $pluginExtForeignKey: String!
    $controls: String!
  ) {
    updateGatewayConsumerPlugin(
      id: $id
      pluginExtForeignKey: $pluginExtForeignKey
      plugin: $controls
    ) {
      id
    }
  }
