query GetServiceAccessPermissions($resourceId: String!, $prodEnvId: ID!) {
  getUmaPoliciesForResource(prodEnvId: $prodEnvId, resourceId: $resourceId) {
    id
    name
    description
    type
    logic
    decisionStrategy
    owner
    clients
    users
    groups
    scopes
  }
  getOrgPoliciesForResource(prodEnvId: $prodEnvId, resourceId: $resourceId) {
    id
    name
    description
    type
    logic
    decisionStrategy
    owner
    clients
    users
    groups
    scopes
  }
}
