
  mutation RevokeAccess(
    $prodEnvId: ID!
    $resourceId: String!
    $tickets: [String]!
  ) {
    revokePermissions(
      prodEnvId: $prodEnvId
      resourceId: $resourceId
      ids: $tickets
    )
  }
