
  query GetCredentialIssuers {
    allCredentialIssuersByNamespace {
      id
      name
      flow
      mode
      owner {
        name
        providerUsername
        email
      }
      environmentDetails
      availableScopes
      clientAuthenticator
      clientRoles
      clientMappers
      apiKeyName
      resourceType
      resourceScopes
      resourceAccessScope
    }
  }
