
  query RequestDetailsBusinessProfile($consumerId: ID!) {
    BusinessProfile(consumerId: $consumerId) {
      institution {
        legalName
        address {
          addressLine1
          addressLine2
          city
          postal
          province
          country
        }
      }
    }
  }
