
  mutation Update($id: ID!, $callbackUrl: String!) {
    updateEnvironmentClient(
      productEnvironmentId: $id
      callbackUrl: $callbackUrl
    ) {
      id
      credentials
      callbackUrl
    }
  }
