
  mutation UpdateConsumerAccess(
    $consumerId: ID!
    $prodEnvId: ID!
    $controls: JSON
  ) {
    updateConsumerAccess(
      consumerId: $consumerId
      prodEnvId: $prodEnvId
      controls: $controls
    )
  }
