
  query GetConsumerProductsAndEnvironments($namespace: String!) {
    allProductsByNamespace(where: { namespace: $namespace }) {
      id
      name
      environments {
        id
        name
        flow
        credentialIssuer {
          name
          availableScopes
          clientRoles
        }
      }
    }
  }
