
  query GetGatewayService($id: ID!) {
    GatewayService(where: {id: $id}) {
      id
      name
      namespace
      tags
      host
      environment {
        id
        name
        active
        flow
        product {
          name
          organization {
            title
          }
          organizationUnit {
            title
          }
        }
      }
      plugins {
        id
        name
      }
      routes {
        id
        name
        hosts
        paths
        methods
      }
      updatedAt
    }
  }
