
  query GetConsumer($serviceAccessId: ID!) {
    getNamespaceConsumerAccess(serviceAccessId: $serviceAccessId) {
      consumer {
        id
        username
      }
      application {
        name
        owner {
          email
          name
          username
        }
      }
      owner {
        name
        username
        email
      }
      labels {
        labelGroup
        values
      }
      prodEnvAccess {
        productName
        environment {
          flow
          name
          id
          additionalDetailsToRequest
        }
        plugins {
          name
        }
        revocable
        serviceAccessId
        authorization {
          defaultClientScopes
        }
        request {
          name
          isIssued
          isApproved
          isComplete
          additionalDetails
        }
        requestApprover {
          name
        }
      }
    }
  }
