
  query GET {
    allNamespaceServiceAccounts(
      orderBy: "createdAt_DESC"
      where: {
        consumerType: client
        application_is_null: true
        productEnvironment_is_null: true
      }
    ) {
      id
      name
      createdAt
    }
    allTemporaryIdentities {
      id
      userId
    }
  }
