
  query GetOrganizationGroupsPermissions($resourceId: ID!, $prodEnvId: ID!) {
    getOrgPoliciesForResource(prodEnvId: $prodEnvId, resourceId: $resourceId) {
      id
      name
      description
      type
      logic
      decisionStrategy
      owner
      clients
      users
      groups
      scopes
    }
  }
