
  query GetCurrentNamespace {
    currentNamespace {
      id
      name
      displayName
      org
      orgUnit
      orgUpdatedAt
      orgEnabled
      orgNoticeViewed
      orgAdmins
    }
  }
