
  query GetConsumers {
    allServiceAccessesByNamespace(first: 200, orderBy: "updatedAt_DESC") {
      consumer {
        id
        username
        aclGroups
        customId
        plugins {
          name
        }
        tags
        updatedAt
      }
      application {
        name
        appId
      }
    }

    allAccessRequestsByNamespace(where: { isComplete_not: true }) {
      id
    }
  }
