
  query GetCredentialIssuers {
    allCredentialIssuersByNamespace {
      id
      name
      flow
      mode
      owner {
        name
        providerUsername
      }
      environments {
        name
        product {
          name
        }
      }
    }
  }
