
  query GetCredentialIssuers {
    allCredentialIssuersByNamespace {
      id
      name
      flow
      mode
      owner {
        name
        username
        email
      }
      environmentDetails
      inheritFrom {
        environmentDetails
      }
      availableScopes
      clientAuthenticator
      clientRoles
      clientMappers
      apiKeyName
      resourceType
      resourceScopes
      resourceAccessScope
    }
  }
