
    query GetActivity(
    $first: Int
    $skip: Int
    $filter: ActivityQueryFilterInput
  ) {
    getFilteredNamespaceActivity(first: $first, skip: $skip, filter: $filter) {
      id
      message
      params
      activityAt
      blob {
        id
      }
    }
  }
