
  query GET {
    currentNamespace {
      id
      name
      displayName
      scopes {
        name
      }
      prodEnvId
      org
      orgUnit
      orgUpdatedAt
      orgEnabled
      orgNoticeViewed
      orgAdmins
    }
  }
