
  query GetControlContent {
    allGatewayServicesByNamespace {
      id
      name
      extForeignKey
      environment {
        id
      }
      routes {
        id
        name
        extForeignKey
      }
    }
  }
