
  query GetConsumers {
    getFilteredNamespaceConsumers {
      id
      consumerType
      username
      labels {
        labelGroup
        values
      }
      lastUpdated
    }

    allServiceAccessesByNamespace(
      first: 200
      orderBy: "updatedAt_DESC"
      where: { consumer: { username_not_starts_with: "sa-" } }
    ) {
      namespace
      consumer {
        id
        username
        aclGroups
        customId
        plugins {
          name
        }
        tags
        updatedAt
      }
      application {
        name
        appId
      }
    }

    allAccessRequestsByNamespace(where: { isComplete_not: true }) {
      id
      name
      additionalDetails
      communication
      createdAt
      requestor {
        name
      }
      application {
        name
      }
      productEnvironment {
        name
      }
    }
  }
