
  query GetOwnedEnvironment($id: ID!) {
    OwnedEnvironment(where: {id: $id}) {
      id
      name
      active
      flow
      appId
      legal {
        id
        title
        reference
      }
      credentialIssuer {
        id
      }
      approval
      additionalDetailsToRequest
      product {
        name
        namespace
        organization {
          name
        }
        environments {
          name
          id
        }
      }
      services {
        name
        id
        updatedAt
      }
    }
  }
