query allServiceAccessesByNamespace {
  allServiceAccessesByNamespace(where: {consumer: {username_not_starts_with: "sa-"}, productEnvironment: {product: {namespace: "erx-demo"}}}) {
    id
    name
    namespace
    consumer {
      username
    }
  }
}
