
  query GetFilterConsumers($namespace: String!) {
    allConsumerScopesAndRoles

    allProductsByNamespace(where: { namespace: $namespace }) {
      name
      id
      environments {
        id
        name
      }
    }
    allConsumerScopesAndRoles
  }
