
  query GetAccessRequestAuth($id: ID!) {
    AccessRequest(where: { id: $id }) {
      productEnvironment {
        credentialIssuer {
          availableScopes
          clientRoles
        }
      }
    }
  }
