
  mutation Remove($consumerId: ID!, $pluginExtForeignKey: String!) {
    deleteGatewayConsumerPlugin(
      id: $consumerId
      pluginExtForeignKey: $pluginExtForeignKey
    ) {
      id
    }
  }
