
  query GetApplicationServices($appId: String!) {
    myServiceAccesses(where: { application: { appId: $appId } }) {
      id
      name
      active
      application {
        name
      }
      productEnvironment {
        id
        name
        product {
          name
        }
      }
    }
  }
