
  mutation UpdateServiceAccessCredential(
    $id: ID!
    $controls: CredentialReferenceUpdateInput
  ) {
    updateServiceAccessCredential(id: $id, controls: $controls) {
      credential
    }
  }
