
  query GetConsumers {
    allServiceAccessesByNamespace(
      first: 200
      orderBy: "updatedAt_DESC"
      where: { productEnvironment_is_null: false }
    ) {
      consumer {
        id
        username
        aclGroups
        customId
        plugins {
          name
        }
        tags
        updatedAt
      }
      application {
        name
        appId
      }
    }

    allAccessRequestsByNamespace(where: { isComplete_not: true }) {
      id
    }
  }
