
  query MyApplications {
    myApplications {
      id
      appId
      description
      name
      owner {
        name
      }
    }
    allTemporaryIdentities {
      id
      userId
    }
  }

