
  query GetConsumerScopesAndRoles($prodEnvId: ID!, $consumerId: ID!) {
    consumerScopesAndRoles(
      prodEnvId: $prodEnvId
      consumerUsername: $consumerUsername
    ) {
      id
      consumerType
      defaultScopes
      optionalScopes
      clientRoles
    }
  }
