
  query GetBusinessProfile($consumerId: ID!) {
    BusinessProfile(serviceAccessId: $consumerId) {
      institution {
        legalName
        address {
          addressLine1
          addressLine2
          city
          postal
          province
          country
        }
        isSuspended
        businessTypeOther
      }
    }
  }
