
  query Get($id: ID!) {
    allProductsByNamespace(where: { id: $id }) {
      id
      name
      environments {
        id
        approval
        name
        active
        flow
        additionalDetailsToRequest
        legal {
          title
          description
          link
          reference
        }
        credentialIssuer {
          clientAuthenticator
        }
      }
    }
    allDiscoverableProducts(where: { id: $id }) {
      id
      name
      environments {
        id
        approval
        name
        active
        flow
        additionalDetailsToRequest
        legal {
          title
          description
          link
          reference
        }
        credentialIssuer {
          clientAuthenticator
        }
      }
    }
    myApplications {
      id
      appId
      name
      owner {
        name
      }
    }
    mySelf {
      legalsAgreed
    }
    allTemporaryIdentities {
      id
      userId
      name
      providerUsername
      email
    }
  }
