
  query GetConsumers($filter: ConsumerQueryFilterInput) {
    allConsumerGroupLabels

    getFilteredNamespaceConsumers(filter: $filter) {
      id
      consumerType
      username
      labels {
        labelGroup
        values
      }
      lastUpdated
    }
  }
