
  mutation GrantAccessToConsumer(
    $prodEnvId: ID!
    $consumerId: ID!
    $controls: JSON
  ) {
    grantAccessToConsumer(
      prodEnvId: $prodEnvId
      consumerId: $consumerId
      controls: $controls
    )
  }
