
  query GET($environmentId: ID!) {
    getAccountLinking(id: $environmentId) {
      linkingUrl
      linkedIdentities
      environment {
        name
        product {
          name
        }
      }
    }
  }
