
  query GetEnvironment($id: ID!) {
    Environment(where: { id: $id }) {
      id
      name
      flow
      appId
      product {
        appId
      }
      credentialIssuer {
        flow
        clientRoles
      }
    }
  }
