import { Type, type Static } from '@sinclair/typebox';

export const ProblemSchema = Type.Object(
  {
    type: Type.String({
      format: 'uri',
      description:
        'A URI reference that identifies the problem type. Should resolve to a human-readable explanation.',
      examples: ['https://errors.sdx.gov.bc.ca/subsystem-not-found'],
    }),
    title: Type.String({
      description:
        'Short, human-readable summary of the problem type. SHOULD NOT change between occurrences.',
      examples: ['Subsystem not found'],
    }),
    status: Type.Integer({
      description:
        'HTTP status code originally generated by the origin server for this occurrence.',
      examples: [404],
    }),
    detail: Type.Optional(
      Type.String({
        description:
          'Human-readable explanation specific to this occurrence of the problem.',
        examples: ['No subsystem with id "claims-xyz"'],
      })
    ),
    instance: Type.Optional(
      Type.String({
        description:
          'URI reference identifying the specific occurrence of the problem.',
        examples: ['/v1/subsystems/claims-xyz'],
      })
    ),
    code: Type.Optional(
      Type.String({
        description:
          'Stable machine-readable identifier for this error class (in addition to `type`).',
        examples: ['SUBSYSTEM_NOT_FOUND'],
      })
    ),
    requestId: Type.Optional(
      Type.String({
        description:
          'Server-generated identifier for the request that produced this problem; useful for log correlation.',
        examples: ['req-7f3a'],
      })
    ),
    errors: Type.Optional(
      Type.Array(
        Type.Object(
          {
            path: Type.Optional(
              Type.String({
                description: 'JSON pointer or path of the offending value.',
                examples: ['/resourceServers/0/services/0/scopes'],
              })
            ),
            message: Type.String({
              description: 'Human-readable validation failure description.',
              examples: ['must be a non-empty array'],
            }),
          },
          { additionalProperties: false }
        ),
        {
          description:
            'Structured per-field validation errors. Present on 400 responses produced by schema validation.',
        }
      )
    ),
  },
  {
    $id: 'Problem',
    additionalProperties: true,
    description:
      'RFC 7807 problem-detail object. Returned with `Content-Type: application/problem+json` for all error responses.',
    examples: [
      {
        type: 'https://errors.sdx.gov.bc.ca/subsystem-not-found',
        title: 'Subsystem not found',
        status: 404,
        detail: 'No subsystem with id "claims-xyz"',
        instance: '/v1/subsystems/claims-xyz',
        code: 'SUBSYSTEM_NOT_FOUND',
        requestId: 'req-7f3a',
      },
    ],
  }
);

export type Problem = Static<typeof ProblemSchema>;
