kind: Product
appId: 2B04C28E08AL
name: API Auto Test Product
dataset: api-auto-test-product
namespace: apipermission
environments:
  - id: 1F7CA929
    name: dev
    active: true
    approval: true
    legal: terms-of-use-for-api-gateway-1
    flow: kong-api-key-acl
    additionalDetailsToRequest: Please provide a bit more of this
    services: []
