name: Build Executable Binary

on:
  push:
    branches: ['dev', 'cypress*']

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Build GWA API Image
        run: |
          git clone https://github.com/bcgov/gwa-cli.git -b dev
          cd gwa-cli

      - name: Download Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20.5'

      - name: Install 'just'
        run: cargo install just

      - name: Build Executable Binary
        run: |
          cd gwa-cli
          just build

      - name: Upload Binary
        uses: actions/upload-artifact@v2
        with:
          name: gwa
          path: /usr/local/bin # Replace with the path to your built binary
        
      - name: Check GWA help
        run: gwa -h