# name of our action
name: "Chromatic Deployment"
# the event that will trigger the action
on:
  pull_request:
    branches:
      - dev

# what the action will do
jobs:
  test:
    # the operating system it will run on
    runs-on: ubuntu-latest
    if: startsWith(github.head_ref, 'component/') == true
    defaults:
      run:
        working-directory: ./src/
    # the list of steps that the action will go through
    steps:
      - uses: actions/checkout@v1
      - run: yarn
      - uses: chromaui/action@v1
        # options required to the GitHub chromatic action
        with:
          workingDir: ./src/
          # our project token, to see how to obtain it
          # refer to https://storybook.js.org/tutorials/intro-to-storybook/react/en/deploy/
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN }}
