name: Scan for Vulnerabilities - Anchore

on:
  push:
    branches: [dev, main, scan/*]

jobs:
  anchore-image-Scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag bcgov/api-services-portal:anchore-scan
      - name: Run the Anchore Scan
        uses: anchore/scan-action@main
        with:
          image: 'bcgov/api-services-portal:anchore-scan'
          acs-report-enable: true
          fail-build: false
      - name: Upload Anchore Scan Results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif
