name: Build Provisioner API

on:
  push:
    branches: [tmp/*, feature/*, dev, test]

permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io
  REGISTRY_USERNAME: ${{ secrets.CONTAINER_REGISTRY_USERNAME }}
  REGISTRY_PASSWORD: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}

jobs:
  image:
    uses: ./.github/workflows/templates
    with:
      name: provisioner
      context: provisioner-api

  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install oc
        uses: redhat-actions/oc-installer@v1
        with:
          version: '4.6'

      - name: Authenticate to silver and set context
        uses: redhat-actions/oc-login@v1
        with:
          openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}
          openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}

          # Disables SSL cert checking. Use this if you don't have the certificate authority data.
          insecure_skip_tls_verify: true

          namespace: ${{ env.OPENSHIFT_NAMESPACE }}

      - name: 'Get Helm'
        if: github.ref != 'refs/heads/dev'
        run: |
          curl -L -O https://get.helm.sh/helm-v3.4.2-linux-amd64.tar.gz
          tar -xf helm-v3.4.2-linux-amd64.tar.gz

      - name: 'Deploy Provisioner API'
        if: github.ref != 'refs/heads/dev'
        run: |
          export PATH=$PATH:`pwd`/linux-amd64

          echo "
          podAnnotations:
            sha: $GITHUB_SHA

          replicaCount: 1

          rollingUpdate:
            maxUnavailable: 50%
            maxSurge: 50%

          image:
            repository: ${{ env.REGISTRY }}/bcgov/api-services-portal/provisioner
            tag: ${{ steps.set-deploy-id.outputs.DEPLOY_ID }}
            pullPolicy: Always

          imagePullSecrets:
            - name: dev-github-read-packages-creds

          podSecurityContext:
            fsGroup: ${{ secrets.RUNNING_UID_GID }}

          securityContext:
            runAsUser: ${{ secrets.RUNNING_UID_GID }}

          containerPort: 3000

          serviceAccount:
            create: false
            name: asp-service-account

          env:
            TZ:
              value: 'America/Los_Angeles'
          " > values.yaml

          helm repo add bcgov http://bcgov.github.io/helm-charts
          helm upgrade --install proto-asp-${{ steps.set-deploy-id.outputs.DEPLOY_ID }}-proapi -f values.yaml --history-max 3 bcgov/generic-api

      - name: Authenticate to Gold and set context
        if: github.ref == 'refs/heads/test'
        uses: redhat-actions/oc-login@v1
        with:
          openshift_server_url: ${{ secrets.OPENSHIFT_GOLD_SERVER }}
          openshift_token: ${{ secrets.OPENSHIFT_GOLD_TOKEN }}
          insecure_skip_tls_verify: true
          namespace: ${{ secrets.OPENSHIFT_GOLD_TEST_NAMESPACE }}

      - name: 'Restart Provisioner API in Gold Test Namespace'
        if: github.ref == 'refs/heads/test'
        run: |
          oc rollout restart deployment/bcgov-provisioner-api-generic-api -n ${{ secrets.OPENSHIFT_GOLD_TEST_NAMESPACE }}
