name: Sync GitHub issues to Jira
on: [issues, issue_comment]

jobs:
  sync-issues:
    name: Sync issues to Jira
    runs-on: ubuntu-latest
    steps:
      - uses: ikethecoder/sync-issues-github-jira@latest
        with:
          webhook-url: ${{ secrets.JIRA_WEBHOOK_URL }}
